title: Yijun Xiang's Homepage
page-top-title: Yijun Xiang
top-section-bg-text: Be what you wanna be
home-subtitle: Yijun Xiang&ensp;|&ensp;向一郡
copyright-text: '&copy; Yijun Xiang 2023-2025. All Rights Reserved.'